pjt/moive-pjt/movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:pk>/', views.detail, name ='detail'),
    path('<int:pk>/update/', views.update, name ='update'),
    path('<int:pk>/delete/', views.delete, name ='delete'),
    path('<int:pk>/comments/', views.comments_create, name='comments_create'),
    path('<int:movie_pk>/comments/<int:comment_pk>/delete',
         views.comments_delete, name='comments_delete'),
    path('<int:movie_pk>/likes/', views.likes, name='likes')
] 

pjt/moive-pjt/mypjt/urls.py
from django.contrib import admin
from django.urls import path, include
from accounts import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('movies/', include('movies.urls')),
    path('<int:user_pk>/password/', views.change_password, name= 'change_password'),
]

pjt/moive-pjt/movies/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone

# Create your models here.
class Movie(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    # 작성자 정보
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, default=1

    )
    like_users = models.ManyToManyField(
        settings.AUTH_USER_MODEL, related_name ='like_movies')


class Comment(models.Model):
    movie = models.ForeignKey(
        Movie, on_delete=models.CASCADE
    )
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE
    )
    content = models.CharField(max_length=300)

pjt/moive-pjt/movies/forms.py
from django import forms
from .models import Movie, Comment

class MovieForm(forms.ModelForm):
    class Meta:
        model = Movie
        fields = ('title','content',)

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('content',)

pjt/moive-pjt/movies/views.py
from django.shortcuts import render, redirect
from .models import Movie, Comment
from .forms import MovieForm, CommentForm
from django.contrib.auth.decorators import login_required

# Create your views here.
def index(request):
    movies = Movie.objects.all()
    context = {
        'movies' : movies,
    }
    return render(request, 'movies/index.html', context)

@login_required
def create(request):
    if request.method == 'POST':
        form = MovieForm(request.POST, request.FILES)
        if form.is_valid():
            movie = form.save()
            return redirect('movies:detail', movie.pk)
    else:
        form = MovieForm()
    context = {
        'form' : form
    }
    return render(request, 'movies/create.html', context)

def detail(request, pk):
    movie = Movie.objects.get(pk=pk)
    comments = movie.comment_set.all()
    comment_form = CommentForm()
    context = {
        'movie' : movie,
        'comments' : comments,
        'comment_form': comment_form,
    }
    return render(request, 'movies/detail.html', context)

@login_required    
def update(request, pk):
    movie = Movie.objects.get(pk=pk)
    if request.method == "POST":
        form = MovieForm(request.POST, request.FILES, instance = movie)
        if form.is_valid():
            form.save()
            return redirect('movies:detail', movie.pk)
    else:
        form = MovieForm(instance=movie)
    context = {
        'movie' : movie,
        'form' : form,
    }
    return render(request, 'movies/update.html', context)

@login_required
def delete(request, pk):
    movie = Movie.objects.get(pk=pk)
    movie.delete()
    return redirect('movies:index')

@login_required
def comments_create(request, pk):
    movie = Movie.objects.get(pk=pk)
    comment_form = CommentForm(request.POST)

    if comment_form.is_valid():
        comment = comment_form.save(commit=False)
        comment.movie = movie
        comment.user = request.user
        comment.save()
        return redirect('movies:detail', movie.pk)
    context = {
        'movie' :  movie,
        'comment_form' : comment_form,
    }
    return render(request, 'movies/detail.html', context)

@login_required
def comments_delete(request, movie_pk, comment_pk):
    movie = Movie.objects.get(pk=movie_pk)
    comment = Comment.objects.get(pk=comment_pk)

    if request.user == comment.user:
        comment.delete()
    return redirect('movies:detail', movie.pk)


@login_required
def likes(request, movie_pk):
    movie = Movie.objects.get(pk=movie_pk)
    if request.user in movie.like_users.all():
        movie.like_users.remove(request.user)
    else:
        movie.like_users.add(request.user)

    return redirect('movies:index')

pjt/moive-pjt/movies/templates/movies/create.html
{% extends "base.html" %}

{% block content %}
<h1>영화 등록 페이지</h1>
        <form action="{% url "movies:create" %}" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value='등록'>
        </form> 
{% endblock content %}

pjt/moive-pjt/movies/templates/movies/detail.html
{% extends "base.html" %}

{% block content %}
<h1>DETAIL PAGE</h1>
    {% if movie.image %}
        <img src=" {{ movie.image.url }}" alt="image">
    {% endif %}
    <h3>{{ movie.title }}</h3>
    <p>{{ movie.content }}</p>
    <hr>

    <h3>댓글 목록</h3>
    {% for comment in comments %}
    <li>{{ comment.content }} </li>
    {% endfor %}

    <hr>
    <form action="{% url "movies:comments_create" movie.pk%}" method="POST">
        {% csrf_token %}
        {{ comment_form }}
        <input type="submit" value='댓글 작성'>
    </form>
    <br>
    <a href="{% url "movies:update" movie.pk %}">수정</a>
    <form action="{% url "movies:delete" movie.pk %}" method="POST">
        {% csrf_token %}
        <input type="submit" value='삭제'>
    </form>
    <a href="{% url "movies:index" %}">돌아가기</a> 
{% endblock content %}

pjt/moive-pjt/movies/templates/movies/index.html
{% extends "base.html" %}

{% block content %}

<h1>INDEX PAGE</h1>

{% for movie in movies %}

<p>{{movie.pk}}. {{ movie.title }}</p>
<p>{{ movie.content }}</p>
<a href="{% url "movies:detail" movie.pk %}">상세 페이지</a>

{% comment %} 좋아요버튼 {% endcomment %}
<form action="{% url "movies:likes" movie.pk %}"method="POST">
  {% csrf_token %}
  {% if request.user in movie.like_users.all %}
    <input type="submit" value='좋아요 취소'>
  {% else %}
     <input type="submit" value='좋아요'>
  {% endif %}
</form>

<hr>
{% endfor %}

{% endblock content %}

pjt/moive-pjt/movies/templates/movies/update.html
{% extends "base.html" %}

{% block content %}

<h1>UPDATE</h1>
    <form action="{% url "movies:update" movie.pk %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value = '수정'>
    </form>
    <hr>
    <a href="{% url "movies:detail" movie.pk %}">[돌아가기]</a>

{% endblock content %}