pjt/moive-pjt/accounts/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('update/', views.update, name='update'),
    path('delete/', views.delete, name='delete'),
    path('profile/<username>/', views.profile, name='profile'),
    path('<int:user_pk>/follow/', views.follow, name='follow'),
    # path('change_password/', views.change_password, name='change_password'),
]

pjt/moive-pjt/movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:pk>/', views.detail, name ='detail'),
    path('<int:pk>/update/', views.update, name ='update'),
    path('<int:pk>/delete/', views.delete, name ='delete'),
    path('<int:pk>/comments/', views.comments_create, name='comments_create'),
    path('<int:movie_pk>/comments/<int:comment_pk>/delete',
         views.comments_delete, name='comments_delete'),
    path('<int:movie_pk>/likes/', views.likes, name='likes')
] 

pjt/moive-pjt/mypjt/urls.py
from django.contrib import admin
from django.urls import path, include
from accounts import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('movies/', include('movies.urls')),
    path('<int:user_pk>/password/', views.change_password, name= 'change_password'),
]

pjt/moive-pjt/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>
  {% if request.user.is_authenticated %}
  <ul class="nav nav-underline">
    <li class="nav-item">
      <a class="nav-link active" aria-current="page" href="{% url "movies:index" %}">MOVIE</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url "movies:create" %}">영화 등록</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url "accounts:update" %}">회원정보수정</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url "accounts:profile" user.username %}">프로필</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url "accounts:logout" %}">로그아웃</a>
    </li>
  </ul>
  
  {% else %}
  <ul class="nav nav-underline">
    <li class="nav-item">
      <a class="nav-link active" aria-current="page" href="{% url "movies:index" %}">MOVIE</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url "accounts:signup" %}">회원가입</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url "accounts:login" %}">로그인</a>
    </li>
  </ul>

  {% endif %}

  {% block content %}
  {% endblock content %}

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>